package com.cmcc.mss.oa_pageinquirydeptemprelationinfosrv;

import root.report.db.DbFactory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-23T16:37:00.639+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "OA_PageInquiryDeptEmpRelationInfoSrv",
                  targetNamespace = "http://mss.cmcc.com/OA_PageInquiryDeptEmpRelationInfoSrv")
public class OAPageInquiryDeptEmpRelationInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mss.cmcc.com/OA_PageInquiryDeptEmpRelationInfoSrv", "OA_PageInquiryDeptEmpRelationInfoSrv");
    public final static QName OAPageInquiryDeptEmpRelationInfoSrvPort = new QName("http://mss.cmcc.com/OA_PageInquiryDeptEmpRelationInfoSrv", "OA_PageInquiryDeptEmpRelationInfoSrvPort");
    static {
        URL url = null;
        String value = null;
        try {
            value = DbFactory.Open(DbFactory.FORM).selectOne("budget.getDicValueByKey","PageInquiryDeptEmpRelationInfoSrv");
            url = new URL(value);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OAPageInquiryDeptEmpRelationInfoSrv_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", value);
        }
        WSDL_LOCATION = url;
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OAPageInquiryDeptEmpRelationInfoSrv_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OAPageInquiryDeptEmpRelationInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryDeptEmpRelationInfoSrvPort")
    public OAPageInquiryDeptEmpRelationInfoSrv getOAPageInquiryDeptEmpRelationInfoSrvPort() {
        return super.getPort(OAPageInquiryDeptEmpRelationInfoSrvPort, OAPageInquiryDeptEmpRelationInfoSrv.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAPageInquiryDeptEmpRelationInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryDeptEmpRelationInfoSrvPort")
    public OAPageInquiryDeptEmpRelationInfoSrv getOAPageInquiryDeptEmpRelationInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(OAPageInquiryDeptEmpRelationInfoSrvPort, OAPageInquiryDeptEmpRelationInfoSrv.class, features);
    }

}
