package com.cmcc.mss.oa_pageinquirydepartmentinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-23T16:34:38.346+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv", name = "OA_PageInquiryDepartmentInfoSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OAPageInquiryDepartmentInfoSrv {

    @WebMethod(action = "process")
    @WebResult(name = "OA_PageInquiryDepartmentInfoSrvResponse", targetNamespace = "http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv", partName = "payload")
    public OAPageInquiryDepartmentInfoSrvResponse process(
        @WebParam(partName = "payload", name = "OA_PageInquiryDepartmentInfoSrvRequest", targetNamespace = "http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv")
        OAPageInquiryDepartmentInfoSrvRequest payload
    );
}
