
package com.cmcc.mss.oa_pageinquirydepartmentinfosrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-23T16:34:38.190+08:00
 * Generated source version: 3.2.4
 *
 */
public final class OAPageInquiryDepartmentInfoSrv_OAPageInquiryDepartmentInfoSrvPort_Client {

    private static final QName SERVICE_NAME = new QName("http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv", "OA_PageInquiryDepartmentInfoSrv");

    private OAPageInquiryDepartmentInfoSrv_OAPageInquiryDepartmentInfoSrvPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OAPageInquiryDepartmentInfoSrv_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OAPageInquiryDepartmentInfoSrv_Service ss = new OAPageInquiryDepartmentInfoSrv_Service(wsdlURL, SERVICE_NAME);
        OAPageInquiryDepartmentInfoSrv port = ss.getOAPageInquiryDepartmentInfoSrvPort();

        {
        System.out.println("Invoking process...");
        com.cmcc.mss.oa_pageinquirydepartmentinfosrv.OAPageInquiryDepartmentInfoSrvRequest _process_payload = null;
        com.cmcc.mss.oa_pageinquirydepartmentinfosrv.OAPageInquiryDepartmentInfoSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
