package com.cmcc.mss.oa_pageinquirydepartmentinfosrv;

import root.report.db.DbFactory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-23T16:34:38.357+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "OA_PageInquiryDepartmentInfoSrv",
                  targetNamespace = "http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv")
public class OAPageInquiryDepartmentInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv", "OA_PageInquiryDepartmentInfoSrv");
    public final static QName OAPageInquiryDepartmentInfoSrvPort = new QName("http://mss.cmcc.com/OA_PageInquiryDepartmentInfoSrv", "OA_PageInquiryDepartmentInfoSrvPort");
    static {
        URL url = null;
        String value = null;
        try {
            value = DbFactory.Open(DbFactory.FORM).selectOne("budget.getDicValueByKey","PageInquiryDepartmentInfoSrv");
            url = new URL(value);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OAPageInquiryDepartmentInfoSrv_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", value);
        }
        WSDL_LOCATION = url;
    }

    public OAPageInquiryDepartmentInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OAPageInquiryDepartmentInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAPageInquiryDepartmentInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OAPageInquiryDepartmentInfoSrv_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OAPageInquiryDepartmentInfoSrv_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OAPageInquiryDepartmentInfoSrv_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OAPageInquiryDepartmentInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryDepartmentInfoSrvPort")
    public OAPageInquiryDepartmentInfoSrv getOAPageInquiryDepartmentInfoSrvPort() {
        return super.getPort(OAPageInquiryDepartmentInfoSrvPort, OAPageInquiryDepartmentInfoSrv.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAPageInquiryDepartmentInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryDepartmentInfoSrvPort")
    public OAPageInquiryDepartmentInfoSrv getOAPageInquiryDepartmentInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(OAPageInquiryDepartmentInfoSrvPort, OAPageInquiryDepartmentInfoSrv.class, features);
    }

}
