#语音查询

POST http://localhost:80/reportServer/nlp/getResult/查询亚信的采购订单 HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}

###列出所有的数据库
POST http://localhost:80/reportServer/DBConnection/ListAll HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}

###hive
POST http://localhost:80/reportServer/finance/getStudents HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
    
}

###hbase
POST http://localhost:80/reportServer/finance/gethbase HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
    
}


###登录请求示例
POST http://localhost:8080/reportServer/user/login HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{ UserCode: "system", Pwd: "KfTaJa3vfLE=" }

###查询所有的函数
POST http://localhost:80/reportServer/function/getAllFunctionName HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}



###查询所有的函数类别
POST http://localhost:80/reportServer/function1/getAllFunctionClass HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}


###查询所有的函数类别
POST http://localhost:80/reportServer/hive/get HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
    func_id:"37"
}


###查询函数用ID
POST http://localhost:80/reportServer/function/getFunctionByID/36 HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
    func_id:"37"
}

#统计指标
GET https://data.stats.gov.cn/easyquery.htm  HTTP/1.1


###保存一个函数
https://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%5D&k1=1604300866921&h=1

###保存一个函数
POST http://localhost:8080/reportServer/function/saveUserSql HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
  "comment": {
    "type": "sql",
    "desc": "bbbb",
    "db": "jlerp",
    "in": [
      {
        "id": "period_year",
        "name": "期间",
        "datatype": "varchar",
        "dict": "",
        "default": "",
        "isformula": "false"
      },
      {
        "id": "period_num",
        "name": "period_num",
        "datatype": "varchar",
        "dict": "",
        "default": "",
        "isformula": "false"
      },
      {
        "id": "segment1",
        "name": "segment1",
        "datatype": "varchar",
        "dict": "",
        "default": "",
        "isformula": "false"
      },
      {
        "id": "segment3",
        "name": "segment3",
        "datatype": "varchar",
        "dict": "",
        "default": "",
        "isformula": "false"
      },
      {
        "id": "segment5",
        "name": "segment5",
        "datatype": "varchar",
        "dict": "",
        "default": "",
        "isformula": "false"
      }
    ],
    "out": [
      {
        "id": "net_bal",
        "name": "net_bal",
        "datatype": "varchar",
        "link": {}
      }
    ]
  },
  "cdata": "SELECT\r\n    ifnull(\r\n        sum(\r\n            gb.PERIOD_NET_DR-gb.PERIOD_NET_CR\r\n        ) ,\r\n        0\r\n    ) net_bal\r\nFROM\r\n    gl_bal_${period_year} gb\r\nWHERE 1=1\r\n     <if test=\"period_num!='' \">\r\n   and gb.PERIOD_NUM=${period_num}\r\n</if>\r\n   AND gb.SEGMENT1 like '${segment1}%'\r\n   and gb.segment3 LIKE '${segment3}%'\r\n     <if test=\"segment5!='' \">\r\n   and gb.segment5 LIKE '${segment5}%'\r\n</if>",
  "namespace": "总账",
  "id": "a987"
}