package com.cmcc.mss.oa_pageinquiryemployeeinfosrv;

import root.report.db.DbFactory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-22T13:04:18.301+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "OA_PageInquiryEmployeeInfoSrv",
                  targetNamespace = "http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv")
public class OAPageInquiryEmployeeInfoSrv_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv", "OA_PageInquiryEmployeeInfoSrv");
    public final static QName OAPageInquiryEmployeeInfoSrvPort = new QName("http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv", "OA_PageInquiryEmployeeInfoSrvPort");
    static {
        URL url = null;
        String value = null;
        try {
            value = DbFactory.Open(DbFactory.FORM).selectOne("budget.getDicValueByKey","PageInquiryEmployeeInfoSrv");
            url = new URL(value);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OAPageInquiryEmployeeInfoSrv_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", value);
        }
        WSDL_LOCATION = url;
    }

    public OAPageInquiryEmployeeInfoSrv_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OAPageInquiryEmployeeInfoSrv_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAPageInquiryEmployeeInfoSrv_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OAPageInquiryEmployeeInfoSrv_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OAPageInquiryEmployeeInfoSrv_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OAPageInquiryEmployeeInfoSrv_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OAPageInquiryEmployeeInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryEmployeeInfoSrvPort")
    public OAPageInquiryEmployeeInfoSrv getOAPageInquiryEmployeeInfoSrvPort() {
        return super.getPort(OAPageInquiryEmployeeInfoSrvPort, OAPageInquiryEmployeeInfoSrv.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAPageInquiryEmployeeInfoSrv
     */
    @WebEndpoint(name = "OA_PageInquiryEmployeeInfoSrvPort")
    public OAPageInquiryEmployeeInfoSrv getOAPageInquiryEmployeeInfoSrvPort(WebServiceFeature... features) {
        return super.getPort(OAPageInquiryEmployeeInfoSrvPort, OAPageInquiryEmployeeInfoSrv.class, features);
    }

}
