package com.cmcc.mss.oa_pageinquiryemployeeinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-22T13:04:18.290+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv", name = "OA_PageInquiryEmployeeInfoSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OAPageInquiryEmployeeInfoSrv {

    @WebMethod(action = "process")
    @WebResult(name = "OA_PageInquiryEmployeeInfoSrvResponse", targetNamespace = "http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv", partName = "payload")
    public OAPageInquiryEmployeeInfoSrvResponse process(
        @WebParam(partName = "payload", name = "OA_PageInquiryEmployeeInfoSrvRequest", targetNamespace = "http://mss.cmcc.com/OA_PageInquiryEmployeeInfoSrv")
        OAPageInquiryEmployeeInfoSrvRequest payload
    );
}
